image: maven:4.0-openjdk-11
default:
  tags:
    -shellocal

stages:
  - test
test:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report
#    - mvn io.qameta.allure:allure-maven:serve
  artifacts:
   paths:
     - target/site/allure-maven-plugin

